org: js24jesp
service: BonzaiHotell

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  stage: dev

  environment:
    TABLE_NAME: ${self:service}-${sls:stage}-main

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:provider.environment.TABLE_NAME}

functions:
  AddRoom:
    handler: functions/AddRoom/index.handler
    events:
      - httpApi:
          path: /add
          method: post

  CancelBooking:
    handler: functions/CancelBooking/index.handler
    events:
      - httpApi:
          path: /cancel
          method: delete

  ChangeBooking:
    handler: functions/ChangeBooking/index.handler
    events:
      - httpApi:
          path: /change
          method: put

  AllBooking:
    handler: functions/AllBooking/index.getAllBookings
    events:
      - httpApi:
          path: /see
          method: get

resources:
  Resources:
    BookingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
